from gym_ergojr.envs.ergo_fight_static_env import ErgoFightStaticEnv
from gym_ergojr.envs.ergo_fight_plus import ErgoFightPlusEnv
from gym_ergojr.envs.ergo_fight_plus_gp import ErgoFightPlusGPEnv
from gym_ergojr.envs.ergo_fight_plus_training import ErgoFightPlusTrainingEnv
from gym_ergojr.envs.ergo_reacher_env import ErgoReacherEnv
from gym_ergojr.envs.ergo_reacher_heavy_env import ErgoReacherHeavyEnv
from gym_ergojr.envs.ergo_reacher_plus import ErgoReacherPlusEnv
from gym_ergojr.envs.ergo_reacher_plus2 import ErgoReacherPlus2Env

from gym_ergojr.envs.ergo_pusher_env import ErgoPusherEnv
from gym_ergojr.envs.ergo_gripper_env import ErgoGripperEnv
from gym_ergojr.envs.ergo_reacher_augmented import ErgoReacherAugmentedEnv
